# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\"E\n\x10RegistrationData\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"+\n\x08\x41uthData\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"H\n\x0fNewNicknameData\x12\x14\n\x0cnew_nickname\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"-\n\nLogoutData\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"J\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\r\n\x05login\x18\x03 \x01(\t\x12\x0c\n\x04info\x18\x04 \x01(\t2\xb6\x01\n\x0b\x41uthService\x12,\n\x08Register\x12\x11.RegistrationData\x1a\t.Response\"\x00\x30\x01\x12 \n\x04\x41uth\x12\t.AuthData\x1a\t.Response\"\x00\x30\x01\x12\x31\n\x0e\x43hangeNickname\x12\x10.NewNicknameData\x1a\t.Response\"\x00\x30\x01\x12$\n\x06Logout\x12\x0b.LogoutData\x1a\t.Response\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRATIONDATA._serialized_start=13
  _REGISTRATIONDATA._serialized_end=82
  _AUTHDATA._serialized_start=84
  _AUTHDATA._serialized_end=127
  _NEWNICKNAMEDATA._serialized_start=129
  _NEWNICKNAMEDATA._serialized_end=201
  _LOGOUTDATA._serialized_start=203
  _LOGOUTDATA._serialized_end=248
  _RESPONSE._serialized_start=250
  _RESPONSE._serialized_end=324
  _AUTHSERVICE._serialized_start=327
  _AUTHSERVICE._serialized_end=509
# @@protoc_insertion_point(module_scope)
