# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import app_pb2 as app__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_stream(
                '/AuthService/Register',
                request_serializer=app__pb2.RegistrationData.SerializeToString,
                response_deserializer=app__pb2.Response.FromString,
                )
        self.Auth = channel.unary_stream(
                '/AuthService/Auth',
                request_serializer=app__pb2.AuthData.SerializeToString,
                response_deserializer=app__pb2.Response.FromString,
                )
        self.ChangeNickname = channel.unary_stream(
                '/AuthService/ChangeNickname',
                request_serializer=app__pb2.NewNicknameData.SerializeToString,
                response_deserializer=app__pb2.Response.FromString,
                )
        self.Logout = channel.unary_stream(
                '/AuthService/Logout',
                request_serializer=app__pb2.LogoutData.SerializeToString,
                response_deserializer=app__pb2.Response.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Auth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeNickname(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_stream_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=app__pb2.RegistrationData.FromString,
                    response_serializer=app__pb2.Response.SerializeToString,
            ),
            'Auth': grpc.unary_stream_rpc_method_handler(
                    servicer.Auth,
                    request_deserializer=app__pb2.AuthData.FromString,
                    response_serializer=app__pb2.Response.SerializeToString,
            ),
            'ChangeNickname': grpc.unary_stream_rpc_method_handler(
                    servicer.ChangeNickname,
                    request_deserializer=app__pb2.NewNicknameData.FromString,
                    response_serializer=app__pb2.Response.SerializeToString,
            ),
            'Logout': grpc.unary_stream_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=app__pb2.LogoutData.FromString,
                    response_serializer=app__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AuthService/Register',
            app__pb2.RegistrationData.SerializeToString,
            app__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Auth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AuthService/Auth',
            app__pb2.AuthData.SerializeToString,
            app__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeNickname(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AuthService/ChangeNickname',
            app__pb2.NewNicknameData.SerializeToString,
            app__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AuthService/Logout',
            app__pb2.LogoutData.SerializeToString,
            app__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
